Components
Kwaleyela-Ikafa/bookstore pull request #1
Opened 2022-09-16 17:58 UTC by Kwaleyela-Ikafa

in this branch we:

- Initialized the project with components

2022-09-16 19:25 UTC, elmar8287 requested changes
Hi, @Kwaleyela-Ikafa.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good PR description 👍 

## Required Changes ♻️

- [ ] Check the comments under the review.

## Optional suggestions
- Please, consider in the future giving the title for commits with the Capital letter - it will make your commits history looks professional

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
![giphy](https://user-images.githubusercontent.com/49064106/180751457-52107e57-31fd-486c-97fe-bcccf4e449af.gif)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 19:25 UTC, elmar8287 commented on src/App.js
> +/* eslint-disable*/
- [ ] Please, consider removing the linter disables from all the code of your app - let linter makes its direct job: find bugs on early steps of the development 👍

2022-09-16 19:25 UTC, elmar8287 commented on src/components/Book.js
> +  <>
- [ ] Please, could you describe from which component these props are coming? Please, consider fixing this issue, to make your app work correctly, as required 👍

2022-09-16 19:25 UTC, elmar8287 commented on src/components/BookList.js
> +export default BookList;
- [ ] I think here you are missing the `Book` component, imported here, and the props which I talked about before should come from here, aka BookList => props => Book

Don't you think?

2022-09-16 19:25 UTC, elmar8287 commented on src/App.js
> +    </div>
- [ ] Please, consider implementing the router, as requered: 

- Has two `Route` s, one for the `BookList` component and the other for the `Categories` component
In order to not show a blank page when visiting the site for the first time, the BookList component should be the default page

```
    <Route exact path="/">
      <BookList />
    </Route>
```

You have to implement the navigation: 

- Should have 2 `<Link>`s in the navbar which leads to the booklist and categories locations

2022-09-17 17:33 UTC, EricMbouwe approved these changes
Hi @Kwaleyela-Ikafa, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- Requested changes ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 17:35 UTC, merged